<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE Enviar_mensaje [
        <!ELEMENT Enviar_mensaje (mensaje)+>
        <!ELEMENT mensaje (remite,destinatario,asunto,texto)>
        <!ELEMENT remite (nombre_R,email_R)>
        <!ELEMENT nombre_R (#PCDATA)>
        <!ELEMENT email_R (#PCDATA)>
        <!ELEMENT destinatario (nombre_D,email_D)>
        <!ELEMENT nombre_D (#PCDATA)>
        <!ELEMENT email_D (#PCDATA)>
        <!ELEMENT asunto (#PCDATA)>
        <!ELEMENT texto (parrafo)+>
        <!ELEMENT parrafo (#PCDATA)>
        ]>
<Enviar_mensaje>
    <mensaje>
        <remite>
            <nombre_R>
                Alfredo Reino
            </nombre_R>
            <email_R>
                alf@ibium.com
            </email_R>
        </remite>
        <destinatario>
            <nombre_D>
                Bill Clinton
            </nombre_D>
            <email_D>
                president@whitehouse.gov
            </email_D>
        </destinatario>
        <asunto>
            Hola Bill
        </asunto>
        <texto>
            <parrafo>
                ¿ Hola qué tal?
            </parrafo>
            <parrafo>
                Hace mucho no escribes. A ver si llamas y quedamos pronto.
            </parrafo>
            <parrafo>Un saludo</parrafo>
        </texto>
    </mensaje>
</Enviar_mensaje>