<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE arboles [
        <!ELEMENT arboles (arbol)*>
        <!ELEMENT arbol (nombre|nombre_comun|vegetacion|altura|forma_estructura|color_primavera|color_otonio|resistencias_heladas)*>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT nombre_comun (#PCDATA)>
        <!ELEMENT vegetacion (#PCDATA)>
        <!ELEMENT altura (#PCDATA)>
        <!ELEMENT forma_estructura (#PCDATA)>
        <!ELEMENT color_primavera (#PCDATA)>
        <!ELEMENT color_otonio (#PCDATA)>
        <!ELEMENT resistencias_heladas (#PCDATA)>
        ]>
<arboles>
    <arbol>
        <nombre>Acer monspessulanum</nombre>
        <nombre_comun>
            Arce de Montpellier, Arce menor
        </nombre_comun>
        <vegetacion>
            Caducifolio
        </vegetacion>
        <altura>
            De 6 a 10 metros
        </altura>
        <forma_estructura>
            Copa esférica.Tronco principal recto con bifurcaciones.Remaje colgante
        </forma_estructura>
        <color_primavera>
            Haz verde brillante, envés verde blanquecino
        </color_primavera>
        <resistencias_heladas>
            Heladas fuertes (hasta -15°C)
        </resistencias_heladas>
    </arbol>
    <arbol>
        <nombre>Olea europea</nombre>
        <nombre_comun>
            Olvio
        </nombre_comun>
        <vegetacion>
            Perenne
        </vegetacion>
        <altura>
            De 8 a 15 metros
        </altura>
        <forma_estructura>
            Copa irregular. Tronco principal irregular con bifurcaciones
        </forma_estructura>
    </arbol>
    <arbol>
        <nombre>Ramaje tortuoso</nombre>
        <color_primavera>
            Haz verde oscuro, envés verde plateado
        </color_primavera>
        <resistencias_heladas>
            Heladas medias (hasta -10°C)
        </resistencias_heladas>
    </arbol>
    <arbol>
        <nombre>Platanus orientalis</nombre>
         <nombre_comun>
            Platano
        </nombre_comun>
        <vegetacion>
            Caducifolio
        </vegetacion>
        <altura>
            De 20 a 25 metros
        </altura>
        <forma_estructura>
            Copa ovoidal. Tronco principal recto.Remaje expandido
        </forma_estructura>
        <color_primavera>
            Haz verde medio, enves verde claro
        </color_primavera>
        <color_otonio>
            Ocre
        </color_otonio>
        <resistencias_heladas>
            Heladas fuertes (hasta -20°C)
        </resistencias_heladas>
    </arbol>
    <arbol>
        <nombre>Quercus ilex</nombre>
        <nombre_comun>
            Encina
        </nombre_comun>
        <vegetacion>
            Perenne
        </vegetacion>
        <altura>
            En torno a 25 metros
        </altura>
        <forma_estructura>
            Copa esférica o elíptica irregular. Tronco principal recto.Ramaje tortuoso
        </forma_estructura>
        <color_primavera>
            Plateado en hojas jóvenes.En hojas antiguas, haz verde oscuro,envés plateado
        </color_primavera>
        <color_otonio>0 </color_otonio>
        <resistencias_heladas>
            Heladas fuertes (hasta -15°C)
        </resistencias_heladas>
    </arbol>
</arboles>