<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Entregas [
        <!ELEMENT Entregas (pedido+)>
        <!ELEMENT pedido (destinario,articulo,direccion_entrega,fecha_entrega)+>
        <!ELEMENT destinario (nombre_D,apellidos)>
        <!ELEMENT nombre_D (#PCDATA)>
        <!ELEMENT apellidos (#PCDATA)>
        <!ELEMENT articulo (nombre,marca)+>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT marca (#PCDATA)>
        <!ELEMENT direccion_entrega (calle,numero,detalles_del_lugar)>
        <!ELEMENT calle (#PCDATA)>
        <!ELEMENT numero (#PCDATA)>
        <!ELEMENT detalles_del_lugar (#PCDATA)>
        <!ELEMENT fecha_entrega (dia,mes,anio)>
        <!ELEMENT dia (#PCDATA)>
        <!ELEMENT mes (#PCDATA)>
        <!ELEMENT anio (#PCDATA)>
        ]>
<Entregas>
    <pedido>
        <destinario>
            <nombre_D>Juan</nombre_D>
            <apellidos>Delgado Mart√≠nez</apellidos>
        </destinario>
        <articulo>
            <nombre>Bicicleta</nombre>
            <marca>Bianchi Oltre</marca>
        </articulo>
        <direccion_entrega>
            <calle>Reforma</calle>
            <numero>423</numero>
            <detalles_del_lugar>tercer piso,letra A</detalles_del_lugar>
        </direccion_entrega>
        <fecha_entrega>
            <dia>19</dia>
            <mes>09</mes>
            <anio>2021</anio>
        </fecha_entrega>
    </pedido>
</Entregas>
